[[Giflib]]
arch = "aarch64"
git-tree-sha1 = "d9ebfef731d18ebf7d006bde07365adfc168cd7f"
os = "macos"

    [[Giflib.download]]
    sha256 = "3d6bf5de31d20b9bb3435443f3008a4e9c642ba506f23338dfa48c26e1e34e57"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.aarch64-apple-darwin.tar.gz"
[[Giflib]]
arch = "aarch64"
git-tree-sha1 = "5295996694dad292f88899d41a338ccb96920401"
libc = "glibc"
os = "linux"

    [[Giflib.download]]
    sha256 = "4512989927dd9fbdf912b54ca2960c98a8fd7430c0e4149f86b588387e335bd0"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.aarch64-linux-gnu.tar.gz"
[[Giflib]]
arch = "aarch64"
git-tree-sha1 = "1707bc78913a803aaab24085d7589f7eedd32af1"
libc = "musl"
os = "linux"

    [[Giflib.download]]
    sha256 = "caa5a96b3f96672b0eee5ba8678d90775c7a44a21b656ffcd888c79ea5ec5dc8"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.aarch64-linux-musl.tar.gz"
[[Giflib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eb16543053d876cf3b6501f7c29095a8442a1eae"
libc = "glibc"
os = "linux"

    [[Giflib.download]]
    sha256 = "501a8334a0bf987819ec0211cc772e0051be0cedeea8455cd8b4445b99629b14"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.armv6l-linux-gnueabihf.tar.gz"
[[Giflib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f00d4ccfa6121c39823791cfcfe8359d51ff78c"
libc = "musl"
os = "linux"

    [[Giflib.download]]
    sha256 = "1099a425a86b98bdb94654b45011d83a4e2fa53111cb6dae5d863cfa2d02c20c"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.armv6l-linux-musleabihf.tar.gz"
[[Giflib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2932fe1bac6a129a7730adf07d9b4ef82473125"
libc = "glibc"
os = "linux"

    [[Giflib.download]]
    sha256 = "84e2e8daf5b40137b6ee7e6a6c3906b33de9ff0997fae2eda9b0a8d0454f5636"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.armv7l-linux-gnueabihf.tar.gz"
[[Giflib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c28ddd5b12d9839943251bb27259d76aaeb2331"
libc = "musl"
os = "linux"

    [[Giflib.download]]
    sha256 = "f6d7a6420890ad56580080f9efccba0e266501ff7c37df3974298ef9c3732d5f"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.armv7l-linux-musleabihf.tar.gz"
[[Giflib]]
arch = "i686"
git-tree-sha1 = "3725294b2253776a467b45d15fca62cf896a31c1"
libc = "glibc"
os = "linux"

    [[Giflib.download]]
    sha256 = "16a77ccab943b6945dfbf0ceb131c3087cb42c098510ae2abaef401948d53b85"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.i686-linux-gnu.tar.gz"
[[Giflib]]
arch = "i686"
git-tree-sha1 = "198dac948c1a03fec2b16247408704ccf070f082"
libc = "musl"
os = "linux"

    [[Giflib.download]]
    sha256 = "6e1832e8ea068f1a9c345c1582057c8db2d4b3541fcd6c2e2952c0fdf0184e98"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.i686-linux-musl.tar.gz"
[[Giflib]]
arch = "i686"
git-tree-sha1 = "482d40dc3a6e3e5d153ff2ee35045cfd6f4ad90c"
os = "windows"

    [[Giflib.download]]
    sha256 = "141353cc6d0e8285054c35d5c5fda610391fb2ce7ec74f8ad59fa2deb93d5eea"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.i686-w64-mingw32.tar.gz"
[[Giflib]]
arch = "powerpc64le"
git-tree-sha1 = "bc3af991b1361d980e9d02620d375f293340e9e5"
libc = "glibc"
os = "linux"

    [[Giflib.download]]
    sha256 = "fbca7eeec67827a4965488d433d7dfd72ab18bb9289860a8ff4516746ce4d726"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.powerpc64le-linux-gnu.tar.gz"
[[Giflib]]
arch = "x86_64"
git-tree-sha1 = "78d048619e81c38ddf7e7a42d5f70db312ec82aa"
os = "macos"

    [[Giflib.download]]
    sha256 = "68742819834c729100157cfdf50b3dd4adfaca1572e18b624dc62fddf67c7c15"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.x86_64-apple-darwin.tar.gz"
[[Giflib]]
arch = "x86_64"
git-tree-sha1 = "c1a171cd18dfbb2e53141187ff8ff347edacaefb"
libc = "glibc"
os = "linux"

    [[Giflib.download]]
    sha256 = "1246586791344d660b4a0deecc038349b58272a98ef29bbc41fdab1506a536fe"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.x86_64-linux-gnu.tar.gz"
[[Giflib]]
arch = "x86_64"
git-tree-sha1 = "29e515ca10714363fbb13391915dc505b6e8fd62"
libc = "musl"
os = "linux"

    [[Giflib.download]]
    sha256 = "a54641208a77350b85726bad5c232cb2c32b7c194037652efc5be876f07f4a28"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.x86_64-linux-musl.tar.gz"
[[Giflib]]
arch = "x86_64"
git-tree-sha1 = "df7590caff2123bcf36fe03404bef19563470935"
os = "freebsd"

    [[Giflib.download]]
    sha256 = "8a386125069cdb5792b2bafd873d3ca8da50b1348ae35ef3cb7c7d31736f8715"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.x86_64-unknown-freebsd.tar.gz"
[[Giflib]]
arch = "x86_64"
git-tree-sha1 = "2f5868436d2606e5721ca530c076ded79f5ec9a1"
os = "windows"

    [[Giflib.download]]
    sha256 = "0c302b1f0ba9e0a166411c08376acd43a5d1ac49007ba7371bc832ffc3e74a08"
    url = "https://github.com/JuliaBinaryWrappers/Giflib_jll.jl/releases/download/Giflib-v5.2.2+0/Giflib.v5.2.2.x86_64-w64-mingw32.tar.gz"
